#
# production settings
# 
# (version: 24, saved: 2022-11-18 18:59:52)
#
---
production:
  settings:
    id: newreplacers
    caption: New Player Characters
    menuvisibile: true
    enabled: true
    storesdata: false
    strings-idspace: 5940
    strings-idstart: 0
    version: 24
    mounters:
      - ".type": CR4ResourceDefinitionsDLCMounter
        resourceDefinitionXmlFilePath: "dlc\\dlcnewreplacers\\data\\gameplay\\globals\\resources\\gameplay.xml"
