#
# production settings
# 
# (version: 579, saved: 2023-12-16 22:28:40)
#
---
production:
  settings:
    id: newreplacers
    caption: New Player Characters
    menuvisibile: true
    enabled: true
    storesdata: true
    strings-idspace: 5940
    strings-idstart: 0
    version: 579
    mounters:
      - ".type": CR4MappinsDLCMounter
        worldFilePath: levels/prolog_village/prolog_village.w2w
        mappinsFilePath: dlc/dlcnewreplacers/data/nr_prologue_pins.w2em
      - ".type": CR4ResourceDefinitionsDLCMounter
        resourceDefinitionXmlFilePath: "dlc\\dlcnewreplacers\\data\\gameplay\\globals\\resources\\gameplay.xml"
      - ".type": CR4RewardsDLCMounter
        rewordsXmlFilePath: "dlc\\dlcnewreplacers\\data\\gameplay\\rewards\\nr_def_rewards.xml"
      - ".type": CR4ScaleformContentDLCMounter
        scaleformDirectoryPath: "dlc\\dlcnewreplacers\\data\\gameplay\\gui_new\\"
      - ".type": CR4DefinitionsDLCMounter
        definitionXmlFilePath: "dlc\\dlcnewreplacers\\data\\gameplay\\abilities\\nr_abilities.xml"
      - ".type": CR4DefinitionsNGPlusDLCMounter
        definitionXmlFilePath: "dlc\\dlcnewreplacers\\data\\gameplay\\abilities_plus\\nr_abilities.xml"
