#
# production settings
# 
# (version: 29, saved: 2022-12-02 19:21:21)
#
---
production:
  settings:
    id: newreplacers
    caption: New Player Characters
    menuvisibile: true
    enabled: true
    storesdata: false
    strings-idspace: 5940
    strings-idstart: 0
    version: 29
    mounters:
      - ".type": CR4ResourceDefinitionsDLCMounter
        resourceDefinitionXmlFilePath: "dlc\\dlcnewreplacers\\data\\gameplay\\globals\\resources\\gameplay.xml"
